# Generated by Django 3.2 on 2021-04-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0002_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
