# Generated by Django 3.2 on 2021-04-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0003_text_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='cols',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='rows',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
